apiVersion: v1
kind: Namespace
metadata:
  name: agents
---
apiVersion: v1
data:
  certificate.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVQkE5aTMxNzVDVHdiY2RZM2RsSmlhS2FHekN3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1RERWVNQndHQTFVRUF3d1ZZVzFqTFdobGJIQmxjaTVoWjJWdWRITXVjM1pqTVFzd0NRWURWUVFHRXdKSgpUakVPTUF3R0ExVUVDQXdGVTNSaGRHVXhEVEFMQmdOVkJBY01CRU5wZEhrd0hoY05NalF3T1RJM01URXhOek16CldoY05NalV3T1RJM01URXhOek16V2pCTU1SNHdIQVlEVlFRRERCVmhiV010YUdWc2NHVnlMbUZuWlc1MGN5NXoKZG1NeEN6QUpCZ05WQkFZVEFrbE9NUTR3REFZRFZRUUlEQVZUZEdGMFpURU5NQXNHQTFVRUJ3d0VRMmwwZVRDQwpBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUxIRSs5cUR3Nkd6aHpuQVJBN21jSkhMCnNySGdzNTdqM3pZMjROUmZITUxnTmhVREwyQ040S1I3UVN0bnMyNVRtM0ZBV3E5dDR4bkxOTE45YmxUZExEejYKcFp4Z1YwZC9nZXZEM2FNeDdjVERURTN0dGpxeUFWeCsyNjNxYmdBR2g3UmQxQkxRVjg4dG5uL3lhMjFSS3kvMgpZRlhLT3AwYzU1aTVoNFZLRmx0empkNHl6T25WODJacVZJWUErQ1dGR2s0SEg3SHVIVmdsN2ZDZWk0LzV2b3RUClV6a0x6dVhxQkVGMVdEY2pPMXFFTVpKM1FhZnJFT0hleG9nSFhWQ1pBMk1pVU9UclZHRlhsRmlWTFliRS9DVEgKU2lwYzUvVlZjSGdXZThkZzIyVTdicGxmb0cxQ0lnbWd6U3duaExQVHBiYkFpRWkwVTFWcjVhOEdkNnhuT2xjQwpBd0VBQWFPQmx6Q0JsREFkQmdOVkhRNEVGZ1FVNWoyWlNSeXM1b0t4L3VodXF0ZE9hbnUwai9jd0h3WURWUjBqCkJCZ3dGb0FVNWoyWlNSeXM1b0t4L3VodXF0ZE9hbnUwai9jd0RnWURWUjBQQVFIL0JBUURBZ1dnTUNBR0ExVWQKSlFFQi93UVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBZ0JnTlZIUkVFR1RBWGdoVmhiV010YUdWcwpjR1Z5TG1GblpXNTBjeTV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLMWxUbXFQSkZSaThFZVBqeDJqCkdTakFyYUZhZXVMQ2F0UXowM1RDWElPR0hkT0U3MUtUUGNSajg2NGpGUWx2V1RaRDhSS1J0T1o2bHZKQmdOTngKZzYrWVNpbFJTeUJFWFRDQUw2bjM4TkFtV2FYOGpwTXEyVlhra25TbUFmT1Rhck1Kbzk4TkwwRnJadVUvZ3BkegpHM0RtMEQxQ2dCU2tUZkUrdnVDOUw0b2xLU0lLMWNuLy9SellGdGJ3cDhyUEVKQkdLSDBoZENwbFVwcmxqNVczCmpUcUQwSmdhc01JbUVzUDE3bThaS3Y1RlRFQ1FPN3FEUVpXNllqQTJPeXpEdThGVDg1UkdrcUkyRG1qUkJxb2UKbWZLcVdlM1Y3bUVtS21yUllnU0xKcTJFTzJjdWJGN1dtbGxKQlpLZkdhTG95Wm44QWk4RFhnWVY5VWVhQnNHeQpablU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  private.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV1d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktVd2dnU2hBZ0VBQW9JQkFRQ3h4UHZhZzhPaHM0YzUKd0VRTzVuQ1J5N0t4NExPZTQ5ODJOdURVWHh6QzREWVZBeTlnamVDa2UwRXJaN051VTV0eFFGcXZiZU1aeXpTegpmVzVVM1N3OCtxV2NZRmRIZjRIcnc5MmpNZTNFdzB4TjdiWTZzZ0ZjZnR1dDZtNEFCb2UwWGRRUzBGZlBMWjUvCjhtdHRVU3N2OW1CVnlqcWRIT2VZdVllRlNoWmJjNDNlTXN6cDFmTm1hbFNHQVBnbGhScE9CeCt4N2gxWUplM3cKbm91UCtiNkxVMU01Qzg3bDZnUkJkVmczSXp0YWhER1NkMEduNnhEaDNzYUlCMTFRbVFOaklsRGs2MVJoVjVSWQpsUzJHeFB3a3gwb3FYT2YxVlhCNEZudkhZTnRsTzI2Wlg2QnRRaUlKb00wc0o0U3owNlcyd0loSXRGTlZhK1d2CkJuZXNaenBYQWdNQkFBRUNnZjlDdGM3bWhGU3NBZWU2aFpiY2d4WDhrVmpRY2JJRlJpM0JQQjBkNzNwSGZ3UlUKR29zT3pHRmdGdURPei9YeHBhK2k1dHRkWTBzODNiY0oxb01mOFQ4eXNnbkpUVHJuQmIyK0dML3pDQU5JcmM4awpWai8vdDdqdU1iSHBSQ0drRGZ4MWpYVWV2Vy9iN1pWMnIzcTA5eWV6d1dScWFPcGoxQVFRSVZNdjYzZm15Z1dOCnVBK2ZVbGt3N1JkUVRYZ1pKTmRUWmVNZXRScmZXWGtuZlQ5RVZZSDc0NkRncnVJVWxFa09YTERjWWRpMktteGUKNTlTblBwc0IwU1M5MU1iWkVDZ0xtUVRZODk5MS9XUFJVUTdBdW9JcE9SbnRCallDeEo0TmpMaWI3Rkl3SkFoTApKU3MrWVRMVmN2K2R0bUJwTUNBUXFhSThGeDlkN3g2RnlIK2FIcUVDZ1lFQTVES0VaNEtHUjQzbEljLzg1UzVFCnVNNHh4UHRlOWx4WER0K2o2aW16ZXlKaWVnenNOeHpkUEpZV2JIb0JhejFUeEtVRk9oMnRkSFhlR1pjMThmUWUKYlk1VXQ5dDFwajQrWDA5VytKbGVkY2pwY1hHYUN6NjU4K1RHVDNiSERwVmhRQzIwTnF4S1NEaDQxOHdJYjdIcQpoaFpsVHVoaWRKRW5iMTZBenJxQjMyRUNnWUVBeDIyZXBwY3I1OUl5cksxV20zajVsakkwblNDcGtQZ2tLYmpOClcyN2N4UWdPWWo3Qm9aeU4vSnFmb0xiWnByNCtkZ0FWbkZrMlhTNkFjYW5uVU5aY2VrU0t6cjFOYUxFZFhlTHEKYW85WVdSZEZySmRuamxLb0JsQmFkN1QwYm5CcUhqY2FWZnhndHRkbDUyaFBzYjQ3TU5KUy9NYzYvOHhZbHRudwpZSklZRExjQ2dZQnNaWjdGZUpnR2gxMnZXUmdkV1lRbGNUVHRDQ2NNeWNKRSszRG1lNWFaU0RVVkd1eGVKYVRsCjhibUhIOUZxdW4vL0toQTRrZjVpRXRkRXVySlNVNDdjcGI2U2Mzb0lWUXJWeFY5ZnlhSzRPbzdCWjZBdjlVVHAKbU9PbXZacEMwQ3laQ3R6UEY3cFZZaFh0RkN0eHUwYlhHTzVZdEVTSWNLY1YzUU04c0JXZklRS0JnRHo3UURBZwp1Y1JCZWsxakU4Q20xV3NnSHdhTkhreStGQkROK2IyandNNWZFRWJxZWJzNWJCRjZGcVhHUS9mQTVNaWdiZnRKCkxGNkNBYlRBQjRPb2lNNjZkdGVRKzBLd0poSzNlSWJ0SGs3ZjF1Wlh4Y3EzYTduQ2lHZGlaZnYvVS9PNVZjeEYKU0MyZzRBQkszVk8wbjlUbCs0cGdRYUpHa2pCT3BEcGpjZ2N4QW9HQkFLMU1yWGZkQzRmdUk4Y3htVFZIb2d3MApHRVErendKaHhQaU9RTFYxSHZRTnFqKzFtSFFhUktpQXJMb2ZUbzI4czNEd0NDZDdUdVA3Yi9yejNDeXRjalZ1CjF4RENDSkZ4TmU5eCt4emVvdTN0bnJwTnNPdHg2cVBqTVdHWGltMHdMbTZ1cnJpbGlFSjJHVHhxSzk2bnZHOUsKZ2lZUDlVS3RCSVFqTkNQRG1iaWgKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  labels:
    app: amc-helper
    component: amc-helper
    partOf: accuknox-agent
  name: amc-helper-tls
  namespace: agents
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: amc-helper
    component: amc-helper
    partOf: accuknox-agent
  name: amc-helper
  namespace: agents
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: amc-helper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: amc-helper
    component: amc-helper
    partOf: accuknox-agent
  name: amc-helper
  namespace: agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amc-helper
  template:
    metadata:
      labels:
        app: amc-helper
        component: amc-helper
        partOf: accuknox-agent
    spec:
      containers:
      - image: safeeraccuknox/demo:accuknox-multi-cluster-setup-server-9c40042
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 5000
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 10
        name: amc-helper
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 200m
            ephemeral-storage: 500Mi
            memory: 500Mi
          requests:
            cpu: 50m
            ephemeral-storage: 100Mi
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          runAsUser: 101
        volumeMounts:
        - mountPath: /certs
          name: certs-volume
          readOnly: true
      securityContext:
        runAsNonRoot: true
      volumes:
      - name: certs-volume
        secret:
          secretName: amc-helper-tls
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app: amc-helper
    component: amc-helper
    partOf: accuknox-agent
  name: amc-helper
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVQkE5aTMxNzVDVHdiY2RZM2RsSmlhS2FHekN3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1RERWVNQndHQTFVRUF3d1ZZVzFqTFdobGJIQmxjaTVoWjJWdWRITXVjM1pqTVFzd0NRWURWUVFHRXdKSgpUakVPTUF3R0ExVUVDQXdGVTNSaGRHVXhEVEFMQmdOVkJBY01CRU5wZEhrd0hoY05NalF3T1RJM01URXhOek16CldoY05NalV3T1RJM01URXhOek16V2pCTU1SNHdIQVlEVlFRRERCVmhiV010YUdWc2NHVnlMbUZuWlc1MGN5NXoKZG1NeEN6QUpCZ05WQkFZVEFrbE9NUTR3REFZRFZRUUlEQVZUZEdGMFpURU5NQXNHQTFVRUJ3d0VRMmwwZVRDQwpBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUxIRSs5cUR3Nkd6aHpuQVJBN21jSkhMCnNySGdzNTdqM3pZMjROUmZITUxnTmhVREwyQ040S1I3UVN0bnMyNVRtM0ZBV3E5dDR4bkxOTE45YmxUZExEejYKcFp4Z1YwZC9nZXZEM2FNeDdjVERURTN0dGpxeUFWeCsyNjNxYmdBR2g3UmQxQkxRVjg4dG5uL3lhMjFSS3kvMgpZRlhLT3AwYzU1aTVoNFZLRmx0empkNHl6T25WODJacVZJWUErQ1dGR2s0SEg3SHVIVmdsN2ZDZWk0LzV2b3RUClV6a0x6dVhxQkVGMVdEY2pPMXFFTVpKM1FhZnJFT0hleG9nSFhWQ1pBMk1pVU9UclZHRlhsRmlWTFliRS9DVEgKU2lwYzUvVlZjSGdXZThkZzIyVTdicGxmb0cxQ0lnbWd6U3duaExQVHBiYkFpRWkwVTFWcjVhOEdkNnhuT2xjQwpBd0VBQWFPQmx6Q0JsREFkQmdOVkhRNEVGZ1FVNWoyWlNSeXM1b0t4L3VodXF0ZE9hbnUwai9jd0h3WURWUjBqCkJCZ3dGb0FVNWoyWlNSeXM1b0t4L3VodXF0ZE9hbnUwai9jd0RnWURWUjBQQVFIL0JBUURBZ1dnTUNBR0ExVWQKSlFFQi93UVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBZ0JnTlZIUkVFR1RBWGdoVmhiV010YUdWcwpjR1Z5TG1GblpXNTBjeTV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLMWxUbXFQSkZSaThFZVBqeDJqCkdTakFyYUZhZXVMQ2F0UXowM1RDWElPR0hkT0U3MUtUUGNSajg2NGpGUWx2V1RaRDhSS1J0T1o2bHZKQmdOTngKZzYrWVNpbFJTeUJFWFRDQUw2bjM4TkFtV2FYOGpwTXEyVlhra25TbUFmT1Rhck1Kbzk4TkwwRnJadVUvZ3BkegpHM0RtMEQxQ2dCU2tUZkUrdnVDOUw0b2xLU0lLMWNuLy9SellGdGJ3cDhyUEVKQkdLSDBoZENwbFVwcmxqNVczCmpUcUQwSmdhc01JbUVzUDE3bThaS3Y1RlRFQ1FPN3FEUVpXNllqQTJPeXpEdThGVDg1UkdrcUkyRG1qUkJxb2UKbWZLcVdlM1Y3bUVtS21yUllnU0xKcTJFTzJjdWJGN1dtbGxKQlpLZkdhTG95Wm44QWk4RFhnWVY5VWVhQnNHeQpablU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: amc-helper
      namespace: agents
      path: /mutate
      port: 5000
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: amc-helper.default.svc
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - agents
  objectSelector:
    matchLabels:
      amc-helper: "true"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - configmaps
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 25
